# Generated by Django 3.1.3 on 2023-10-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.TextField(blank=True)),
                ('color', models.CharField(max_length=100)),
                ('kilometraje', models.IntegerField()),
                ('año', models.IntegerField()),
                ('imagen_url', models.TextField(blank=True)),
            ],
        ),
    ]
