# Generated by Django 3.1.3 on 2023-10-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20231009_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='año',
            new_name='ano',
        ),
    ]
