# Generated by Django 3.1.3 on 2023-10-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_auto_20231011_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='kilometraje',
            new_name='matricula',
        ),
    ]
