# Generated by Django 3.1.3 on 2023-11-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_auto_20231013_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='matricula',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
    ]
