# Generated by Django 3.1.3 on 2023-11-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0007_auto_20231117_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autos.propietario'),
        ),
    ]
