# Generated by Django 3.1.3 on 2023-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0009_auto_20231117_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='ano',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
