apiVersion: v1
kind: ConfigMap
metadata:
 name: psychodivto-config
 labels:
   app: postgres
data:
 PROD_SECRET_KEY: django_sistem_autos
 PROD_DATABASE: postgres
 PROD_USER: postgres
 PROD_PASSWORD: postgres
 PROD_HOST: localhost
 PROD_PORT: "5432"
