apiVersion: v1
kind: ConfigMap
metadata:
 name: psychodivto-config
 labels:
   app: sistema_autos
data:
 PROD_SECRET_KEY: django_sistem_autos
 PROD_DATABASE: sistema_autos
 PROD_USER: divto
 PROD_PASSWORD: divtopc27
 PROD_HOST: localhost
 PROD_PORT: "5432"
