apiVersion: apps/v1
kind: Deployment
metadata:
  name: psychodivto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psychodivto
  template:
    metadata:
      labels:
        app: psychodivto
    spec:
      containers:
      - image: okteto.dev/psychodivto:latest
        name: psychodivto
        envFrom:
        - configMapRef:
            name: psychodivto-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: psychodivto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "psychodivto"
    port: 5432
  selector:
    app: psychodivto