# Generated by Django 4.2.30 on 2026-05-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_auto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteccionPlaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_captura', models.ImageField(upload_to='capturas_anpr/')),
                ('matricula_leida', models.CharField(blank=True, max_length=100, null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('auto_registrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.auto')),
            ],
        ),
    ]
